### PR TITLE
Feat: implement utf8_text for WASM

### LINKED ISSUE #34: Is it possible to implement Node::utf8_text for wasm?
Thanks for your great project!
 
Recently, I'm trying to move my application(made with rust and tree-sitter) to wasm. And I found this crate really suitable. But after I managed to make everything work, I found that `utf8_text` function is unimplemented. Is it possible to implement this function?

### PR DESCRIPTION
**Pull request by Sarrus1**
This PR implements [this suggestion](https://github.com/silvanshade/tree-sitter-facade/issues/34#issuecomment-909405173) and fixes #34.

Please let me know if there is anything you would want me to improve.

### CODE REVIEW

**Comment by silvanshade** [comment]
Thanks for the PR! I've added some feedback in the review comments but once addressed I'm happy to merge this.

**Comment by Sarrus1** [comment]
> I've added some feedback in the review comments 

I might be wrong but I don't see any review comments. In the meantime, I have reverted the mess up from my `cargo fmt` config 👍.

**Comment by silvanshade** [comment]
Thanks for addressing the formatting changes. I'm not sure why you aren't able to see the other review comment but the other one was asking to change from this:

```rust
pub fn utf8_text<'a>(&self, _source: &'a [u8]) -> Result<&'a str, std::str::Utf8Error> {
    std::str::from_utf8(&_source[(self.start_byte() as usize) .. (self.end_byte() as usize)])
}
```

to this:

```rust
pub fn utf8_text<'a>(&self, _source: &'a [u8]) -> Result<Cow<'a, str>, std::str::Utf8Error> {
    std::str::from_utf8(&_source[(self.start_byte() as usize) .. (self.end_byte() as usize)]).map(Into::into)
}
```

This is in order to keep the types consistent with the existing native implementation.

**Comment by Sarrus1** [comment]
> I'm not sure why you aren't able to see the other review comment

I can't see any of them.
Hopefully https://github.com/silvanshade/tree-sitter-facade/pull/55/commits/0c373dab6f9ad569d46a92d3de278f8588ec51b0 did not break the formatting again, for some reason it uses a different formatting style than your config...

**Comment by silvanshade** [comment]
> Hopefully [0c373da](https://github.com/silvanshade/tree-sitter-facade/commit/0c373dab6f9ad569d46a92d3de278f8588ec51b0) did not break the formatting again, for some reason it uses a different formatting style than your config...

If you are using rust-analyzer I believe it should pick up the settings it can apply from the `rustfmt.toml` file, but I am also relying on some nightly features. As long as you run `cargo xtask format` or `cargo +nightly fmt --all` before pushing, it should be fine. But it looks like it went through okay here anyway.

And thanks for making those changes!

**Pull request merged**
